- rpm/harbour-advanced-camera.spec
> [packaging] Fix QtMultimedia dependency.

- qml/pages/CameraUI.qml
When changing focus mode always reset the focus circel back to centre
If in Auto or Macro mode perform a searchAndLock when clicking to focus
Other focus modes will not use the focus circle
> [focus] Better focus mode handling

- qml/pages/CameraUI.qml
- qml/pages/GalleryUI.qml
Also renamed photoList to fileList and photoPath to filePath for (future) consistency,
and pass the real path not URL so it can be used directly with FileEngine.
> [ui] gallery: add delete and close buttons

- qml/components/RoundButton.qml
- qml/pages/CameraUI.qml
- qml/pages/SettingsOverlay.qml
when in auto/macro/continuous, searchAndLock before taking an image
also fixes bug where setting focus mode on startup doesnt work
> [focus] better focus handling

- translations/harbour-advanced-camera-fi.ts
> Add Finnish translations

- harbour-advanced-camera.pro
- qml/pages/GalleryUI.qml
- src/fsoperations.cpp
- src/fsoperations.h
- src/harbour-advanced-camera.cpp
this will allow easier access to the jolla store as Nemo.Filemanger is not allowed
> Remove use of Nemo.Filemanager by adding a simple cpp class to delete files

- qml/pages/CameraUI.qml
- src/effectsmodel.cpp
- src/exposuremodel.cpp
- src/flashmodel.cpp
- src/focusmodel.cpp
- src/fsoperations.cpp
- src/isomodel.cpp
- src/resolutionmodel.cpp
- src/wbmodel.cpp
- translations/harbour-advanced-camera-fr.ts
Remember previously used camera on restart. Style cleanup of c++ models.
> Fix crash caused by missing initial resolution

- translations/harbour-advanced-camera-de.ts
> Updated German translation

- translations/harbour-advanced-camera-fr.ts
> Updated French translation

- translations/harbour-advanced-camera-sv.ts
> Updated Swedish translation

- harbour-advanced-camera.pro
- qml/pages/CameraUI.qml
- rpm/harbour-advanced-camera.spec
- rpm/harbour-advanced-camera.yaml
- src/harbour-advanced-camera.cpp
- src/resourcehandler.cpp
- src/resourcehandler.h
I added a simple zoom slider and zooming using the volume keys.
> Digital zoom support

- qml/pages/CameraUI.qml
- qml/pages/Settings.qml
- qml/pages/SettingsOverlay.qml
Add a setting for swapping the zoom controls around
> [settings] add a dock for general settings

- qml/pages/CameraUI.qml
- qml/pages/GridOverlay.qml
- qml/pages/Settings.qml
- qml/pages/SettingsOverlay.qml
- rpm/harbour-advanced-camera.yaml
- translations/harbour-advanced-camera-de.ts
- translations/harbour-advanced-camera-es.ts
- translations/harbour-advanced-camera-fi.ts
- translations/harbour-advanced-camera-fr.ts
- translations/harbour-advanced-camera-sv.ts
- translations/harbour-advanced-camera-zh_CN.ts
- translations/harbour-advanced-camera.ts
I added an qml only grid overlay. It is configured with a ComboBox in the general settings view.
I also added added qsTr to "switch zoom control".
> simple grid overlay added

- qml/pages/CameraUI.qml
- qml/pages/GalleryUI.qml
- qml/pages/SettingsOverlay.qml
- translations/harbour-advanced-camera-fr.ts
Allows taking photos in portrait orientation with the UI rotating aswell. 
(Not everything is perfect yet but very usable)
> Add portrait orientation photo taking mode

- qml/pages/CameraUI.qml
- qml/pages/GalleryUI.qml
- qml/pages/VideoPlayer.qml
Changed the gallery to use Nemo.Thumbnailer so it can show videos.
Added basic video player page (play, pause, slider).
> [ui] gallery: add support for video thumbnail and basic player

- qml/harbour-advanced-camera.qml
- qml/pages/CameraUI.qml
- qml/pages/SettingsOverlay.qml
- translations/harbour-advanced-camera-fr.ts
Main points of the change are:
Moved the videooutput to the application
addedviewfinderOrientation which controls the rotation of a new controlsContainer, which encapsulates all the buttons on the UI
Moved the focuscircle and mouseare out of the controlsContainer, and correctly handle all the orientations when setting the focus point.
Only display the focuscircle when focuspointmode is manual.
> [wip] Rotation

- qml/components/DockedListView.qml
- qml/pages/SettingsOverlay.qml
- translations/harbour-advanced-camera-fi.ts
- translations/harbour-advanced-camera-fr.ts
- translations/harbour-advanced-camera-sv.ts
Update Finnish translation and fix some small issues in Swedish and French translations.
> Fix menu margins in portrait mode. Add fade to long menu texts.

- qml/pages/CameraUI.qml
> [videoplayer] Fix playing after regaining focus

- qml/pages/CameraUI.qml
- qml/pages/SettingsOverlay.qml
Simplifies the code a bit as a lot of the complexity wasnt required
> [resolution] Fix setting the resolution when switching camera

- harbour-advanced-camera.pro
- qml/pages/CameraUI.qml
- rpm/harbour-advanced-camera.spec
- src/harbour-advanced-camera.cpp
I tried to use `dateTimeOriginal` first, but without success. `date` property works properly and photos even contains time...
> setup camera manufacturer and model in metadata

- harbour-advanced-camera.pro
- qml/pages/CameraUI.qml
- rpm/harbour-advanced-camera.spec
- src/deviceinfo.cpp
- src/deviceinfo.h
- src/harbour-advanced-camera.cpp
it seems that ssu-sysinfo library is not allowed in Harbour
> load libssusysinfo at runtime, to comply Harbour rules

- harbour-advanced-camera.pro
- qml/components/AboutMedia.qml
- qml/pages/AboutImage.qml
- qml/pages/AboutVideo.qml
- qml/pages/GalleryUI.qml
- rpm/harbour-advanced-camera.spec
- rpm/harbour-advanced-camera.yaml
- src/exifmodel.cpp
- src/exifmodel.h
- src/fsoperations.cpp
- src/fsoperations.h
- src/harbour-advanced-camera.cpp
- src/metadatamodel.cpp
- src/metadatamodel.h
I really like metadata info feature written by @vknecht , but it is stalled for year already. So I slightly improved it (using `DetailItem` component), rebased it on current master branch and offer it as separate pull request.
> Media metadata

- src/storagemodel.cpp
- src/storagemodel.h
See this forum thread for more details: https://forum.sailfishos.org/t/advanced-camera-q-how-can-i-force-ac-to-save-photos-and-videos-to-the-sd-card/13219/3
> improve SD card mount point detection
